micronaut:
  application:
    name: GraalVM + Micronaut + Profile Guided Optimization

datasources:
  default:
    url: jdbc:h2:mem:pgo;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;MODE=MYSQL
    username: 'pgo'
    password: 'e5c93586-97d9-4609-ad5d-333e46acdd94'
    driverClassName: org.h2.Driver
    dialect: H2

flyway:
  datasources:
    default:
      locations: classpath:db/migration

jpa:
  default:
    properties:
      hibernate:
        hbm2ddl:
          auto: none

netty:
  default:
    allocator:
      max-order: 3
